[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "24.7.0"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
